/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/serving/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActivationEndpoints implements ActivationEndpointInterface
type FakeActivationEndpoints struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var activationendpointsResource = schema.GroupVersionResource{Group: "networking.internal.knative.dev", Version: "v1alpha1", Resource: "activationendpoints"}

var activationendpointsKind = schema.GroupVersionKind{Group: "networking.internal.knative.dev", Version: "v1alpha1", Kind: "ActivationEndpoint"}

// Get takes name of the activationEndpoint, and returns the corresponding activationEndpoint object, and an error if there is any.
func (c *FakeActivationEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activationendpointsResource, c.ns, name), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// List takes label and field selectors, and returns the list of ActivationEndpoints that match those selectors.
func (c *FakeActivationEndpoints) List(opts v1.ListOptions) (result *v1alpha1.ActivationEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activationendpointsResource, activationendpointsKind, c.ns, opts), &v1alpha1.ActivationEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActivationEndpointList{ListMeta: obj.(*v1alpha1.ActivationEndpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActivationEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested activationEndpoints.
func (c *FakeActivationEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activationendpointsResource, c.ns, opts))

}

// Create takes the representation of a activationEndpoint and creates it.  Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *FakeActivationEndpoints) Create(activationEndpoint *v1alpha1.ActivationEndpoint) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activationendpointsResource, c.ns, activationEndpoint), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// Update takes the representation of a activationEndpoint and updates it. Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *FakeActivationEndpoints) Update(activationEndpoint *v1alpha1.ActivationEndpoint) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activationendpointsResource, c.ns, activationEndpoint), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// Delete takes name of the activationEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeActivationEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activationendpointsResource, c.ns, name), &v1alpha1.ActivationEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActivationEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activationendpointsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActivationEndpointList{})
	return err
}

// Patch applies the patch and returns the patched activationEndpoint.
func (c *FakeActivationEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activationendpointsResource, c.ns, name, data, subresources...), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}
