/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/serving/pkg/apis/networking/v1alpha1"
	scheme "github.com/knative/serving/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActivationEndpointsGetter has a method to return a ActivationEndpointInterface.
// A group's client should implement this interface.
type ActivationEndpointsGetter interface {
	ActivationEndpoints(namespace string) ActivationEndpointInterface
}

// ActivationEndpointInterface has methods to work with ActivationEndpoint resources.
type ActivationEndpointInterface interface {
	Create(*v1alpha1.ActivationEndpoint) (*v1alpha1.ActivationEndpoint, error)
	Update(*v1alpha1.ActivationEndpoint) (*v1alpha1.ActivationEndpoint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ActivationEndpoint, error)
	List(opts v1.ListOptions) (*v1alpha1.ActivationEndpointList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActivationEndpoint, err error)
	ActivationEndpointExpansion
}

// activationEndpoints implements ActivationEndpointInterface
type activationEndpoints struct {
	client rest.Interface
	ns     string
}

// newActivationEndpoints returns a ActivationEndpoints
func newActivationEndpoints(c *NetworkingV1alpha1Client, namespace string) *activationEndpoints {
	return &activationEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the activationEndpoint, and returns the corresponding activationEndpoint object, and an error if there is any.
func (c *activationEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.ActivationEndpoint, err error) {
	result = &v1alpha1.ActivationEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("activationendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ActivationEndpoints that match those selectors.
func (c *activationEndpoints) List(opts v1.ListOptions) (result *v1alpha1.ActivationEndpointList, err error) {
	result = &v1alpha1.ActivationEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("activationendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested activationEndpoints.
func (c *activationEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("activationendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a activationEndpoint and creates it.  Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *activationEndpoints) Create(activationEndpoint *v1alpha1.ActivationEndpoint) (result *v1alpha1.ActivationEndpoint, err error) {
	result = &v1alpha1.ActivationEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("activationendpoints").
		Body(activationEndpoint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a activationEndpoint and updates it. Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *activationEndpoints) Update(activationEndpoint *v1alpha1.ActivationEndpoint) (result *v1alpha1.ActivationEndpoint, err error) {
	result = &v1alpha1.ActivationEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("activationendpoints").
		Name(activationEndpoint.Name).
		Body(activationEndpoint).
		Do().
		Into(result)
	return
}

// Delete takes name of the activationEndpoint and deletes it. Returns an error if one occurs.
func (c *activationEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("activationendpoints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *activationEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("activationendpoints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched activationEndpoint.
func (c *activationEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActivationEndpoint, err error) {
	result = &v1alpha1.ActivationEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("activationendpoints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
